version: "3"
includes:
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web
env:
  DISABLE_NFC: true

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list

  build:
    deps: [web:build]
    desc: Build the application
    cmds:
      - go build -o bin/wrc-laptimer cmd/wrc-laptimer/main.go
    sources:
      - "**/*.go"
    generates:
      - bin/wrc-laptimer

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./bin/wrc-laptimer

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
