version: "3"

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list

  build:
    desc: Build the application
    cmds:
      - go build -o bin/wrc-laptimer .
    sources:
      - "**/*.go"
    generates:
      - bin/wrc-laptimer

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./bin/wrc-laptimer

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
